# Generated by Django 2.2.5 on 2019-09-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=250)),
                ('codigo_producto', models.CharField(max_length=255, unique=True)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descripcion_categoria', models.TextField()),
                ('Bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Bodega')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
            ],
        ),
    ]
