# Generated by Django 2.2.5 on 2019-09-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion_categoria',
            new_name='descripcion_producto',
        ),
    ]
