# Generated by Django 2.2.5 on 2019-09-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190924_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_stock',
            field=models.IntegerField(default=0),
        ),
    ]
