# Generated by Django 2.2.5 on 2019-09-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(max_length=250)),
                ('descripcion_cliente', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=250)),
                ('empresa', models.CharField(max_length=250)),
                ('nit', models.CharField(max_length=250)),
                ('numero_telefono', models.IntegerField(default=0)),
                ('numero_celular', models.IntegerField(default=0)),
                ('correo_electronico', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(max_length=250)),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.Ciudad')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.Departamento')),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.TipoCliente')),
            ],
        ),
    ]
