# Generated by Django 2.2.5 on 2019-09-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_celular',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_telefono',
            field=models.BigIntegerField(),
        ),
    ]
