# Generated by Django 2.2.5 on 2019-09-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190924_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='empresa',
        ),
    ]
