# Generated by Django 2.2.5 on 2019-09-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nit',
            new_name='cedula_nit',
        ),
    ]
